# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: run-cmake
      uses: lukka/run-cmake@v2.0
      with:
        # Select the mode of the action. There are three different modes: CMakeListsTxtBasic: Run CMake using a CMakeLists.txt - Basic configuration, CMakeListsTxtAdvanced: Run CMake using a CMakeLists.txt - Advanced configuration, CMakeSettingsJson: Run CMake using a CMakeSettings.json of Visual Studio.
        cmakeListsOrSettingsJson: CMakeSettingsJson
        # Path to CMakeLists.txt. Used for both CMakeListsTxtBasic and CMakeListsTxtAdvanced modes.
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        # Path to CMakeSettings.json. Used for CMakeSettingsJson mode.
        cmakeSettingsJsonPath: ${{ github.workspace }}/CMakeSettings_GA.json
    
    - name: list dirs
      run: ls ${{ github.workspace }}

    - name: run-test-target
      run: labquest_test
    